# Generated by Django 3.2.16 on 2023-01-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Номер телефона'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='addres',
            new_name='phone_number',
        ),
    ]
