# Generated by Django 3.2.16 on 2023-01-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230103_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
