# Generated by Django 3.2.16 on 2023-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Профиль пользователя'},
        ),
        migrations.AddField(
            model_name='profile',
            name='comet',
            field=models.CharField(blank=True, max_length=150, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='domofon',
            field=models.IntegerField(blank=True, default=0, max_length=10, verbose_name='Домофон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='etaj',
            field=models.IntegerField(blank=True, default=0, max_length=10, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kvartir',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квартира/офис'),
        ),
        migrations.AddField(
            model_name='profile',
            name='podezd',
            field=models.IntegerField(blank=True, default=0, max_length=20, verbose_name='Подъезд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='addres',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=10, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
