# Generated by Django 3.2.16 on 2023-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20230103_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domofon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Домофон'),
        ),
    ]
