# Generated by Django 3.2.16 on 2023-01-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_domofon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='etaj',
            field=models.CharField(blank=True, max_length=10, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='podezd',
            field=models.CharField(blank=True, max_length=20, verbose_name='Подъезд'),
        ),
    ]
