# Generated by Django 3.2.16 on 2023-01-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domofon',
            field=models.CharField(max_length=10, verbose_name='Удобный способ оплаты'),
        ),
    ]
