# Generated by Django 3.2.16 on 2023-01-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230103_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=2, max_length=32, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
