# Generated by Django 3.2.16 on 2023-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adders',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
