# Generated by Django 3.2.16 on 2023-01-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_adders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
