# Generated by Django 3.2.16 on 2023-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20230105_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Корзина', 'Корзина'), ('Ожидает платежа', 'Ожидает платежа'), ('Оплачено', 'Оплачено')], default='Корзина', max_length=32, verbose_name='Cтатус'),
        ),
    ]
